// GENERATED FILE. Do not edit by hand.
// Source: /data/corpus/*.md  ->  npm run build:corpus
// 31 documents, generated 2026-08-27.

export type Department = 'gtm' | 'product' | 'engineering' | 'ga' | 'ops';
export type Sensitivity = 'public' | 'internal' | 'phi-restricted';

export type Doc = {
  id: string;
  title: string;
  department: Department;
  source: string;
  owner: string;
  updated: string;
  sensitivity: Sensitivity;
  body: string;
};

export type DocMeta = Omit<Doc, 'body'>;

export const CORPUS: Doc[] = [
  {
    "id": "eng-architecture-overview",
    "title": "Architecture overview",
    "department": "engineering",
    "source": "github",
    "owner": "Nakul R",
    "updated": "2026-06-28",
    "sensitivity": "internal",
    "body": "# Architecture overview\n\nOne page. Deliberately.\n\n## Flow\n\n1. **Ingest.** We pull tomorrow's and the following day's appointment schedule from the customer's\n   PMS. Open Dental via API, Carestack via API, Eaglesoft via a SQL replica read, Dentrix Ascend via\n   partner API (pending). Runs hourly.\n2. **Dedupe and enrich.** Match the appointment to a patient record and an insurance plan record.\n   Drop anything verified in the last 30 days unless the plan changed.\n3. **Agent pass.** A payer-specific agent handles the portal: authenticate, search the member, parse\n   the eligibility and benefit response, extract frequency history. Each agent is a prompt plus a\n   parser plus a payer playbook loaded from the ops corpus.\n4. **Confidence scoring.** Every extracted field carries a confidence. A verification is high\n   confidence only if every field required by the treatment plan is high confidence. Rules can\n   override: Guardian ortho always goes to a human regardless of confidence.\n5. **Human queue.** Low confidence or rule-triggered verifications land in the HITL queue with the\n   exception reason attached.\n6. **Output.** Verification record written to our store, returned to the customer, and written back\n   to the PMS where write-back is enabled.\n\n## Stores\n\n- Postgres for verification records, appointments, customers, users\n- Object store for raw portal responses, retained 90 days, encrypted at rest\n- No PHI in logs. This is enforced by a redaction layer, not by convention\n\n## Agents\n\nFive payer agents in production covering the top 5 by volume. The remaining payers run a generic\nagent with a lower success rate, which is most of why UHC and BCBS sit at 5.1% and 6.4% exception\nrates. Generic agent replacement is not a Q3 item.\n\n## Deliberate omissions\n\n- No vector database. Playbooks are short and payer-scoped, we load the relevant one directly.\n- No queue infrastructure beyond Postgres row locking. At 240k lifetime verifications we do not\n  need it and it would be another thing to page someone about.\n- No microservices. One deployable.\n\n## The thing that will need to change first\n\nConfidence scoring is per-field and hand-tuned. It has no ground truth to calibrate against because\nwe never learn whether a verification was correct, only whether it was hard. PRD-014 is the first\nstep toward fixing that."
  },
  {
    "id": "eng-eaglesoft-sync-issues",
    "title": "Eaglesoft sync known issues",
    "department": "engineering",
    "source": "github",
    "owner": "Tom Beckett",
    "updated": "2026-08-19",
    "sensitivity": "internal",
    "body": "# Eaglesoft sync, known issues\n\nEaglesoft has no usable public API for what we need. We read from a SQL Server replica the customer\nmaintains. This works but every known issue below is a consequence of that choice.\n\n## Known issues\n\n**1. Replica lag (severity: high)**\nWe read from the customer's replica, not their primary. If replication falls behind, we pull a stale\nschedule and verify appointments that have been cancelled or moved. At Bright Smile's scale, 34\nlocations into one central replica in Plano, this is the main scoping risk. Before any Eaglesoft\ndeal, get their replication schedule and lag monitoring in writing.\n\nMitigation in place: we compare the max appointment modified timestamp against wall clock and skip\nthe sync if the gap exceeds 90 minutes. This means we silently do nothing rather than doing\nsomething wrong, which is correct but invisible. There is no alert. Should be.\n\n**2. Schema variance across versions (severity: medium)**\nEaglesoft installs drift. Column names on the insurance tables differ between 21.x and 23.x, and at\nleast one customer has a vendor-customised schema. We maintain a per-customer column map. Adding a\nnew Eaglesoft customer is a day of schema mapping, not an afternoon.\n\n**3. No write-back (severity: medium, accepted)**\nWe do not write to Eaglesoft. Writing to a customer's SQL Server directly is not something we are\nwilling to do. Eaglesoft customers receive verification results in the Needletail UI and via CSV\nexport. Sales must not imply otherwise.\n\n**4. Character encoding on patient names (severity: low)**\nOlder installs use a non-UTF8 collation. Names with accents come through mangled, which breaks\nmember search on payer portals. Normalisation layer handles most of it, occasional manual fix.\n\n**5. No claim status data (severity: low today, blocking for PRD-014)**\nThe replica does not contain claim status in a usable form. PRD-014 v1 will either screen scrape or\ndefer Eaglesoft. Open question in the PRD."
  },
  {
    "id": "eng-oncall-notes",
    "title": "On-call notes, July and August 2026",
    "department": "engineering",
    "source": "slack",
    "owner": "Wes Okafor",
    "updated": "2026-08-22",
    "sensitivity": "phi-restricted",
    "body": "# On-call notes\n\nRunning log from #eng-oncall. Newest first. Verification IDs only, no member identifiers.\n\n## 2026-08-22, Fri\nPortal change detector fired three times overnight on Cigna. All three false positives, promotional\nbanner. This is NT-318. I am muting the Cigna channel until that ticket is picked up, which I am\naware is exactly the failure mode described in the ticket.\n\n## 2026-08-11, Mon\nUHC portal timeouts spiked to 22% of attempts between 06:00 and 09:00 ET. Not our side. Added a\nretry with exponential backoff as a stopgap, brought effective failure to 9%. Proper fix is in the\nQ3 roadmap.\n\n## 2026-07-22, Tue\nSummit Dental Collective: 60 Aetna verifications went out without the posterior composite downgrade\nnote. Root cause was a rule scoping change deployed 2026-07-20 that narrowed the code set to D2391\nand D2393 only, dropping D2392 and D2394. My change, my mistake. Reverted same day, 60 verifications\nre-issued with the note. Ticket NT-312 will make this rule harder to get wrong.\n\n## 2026-07-09, Wed\nAetna eligibility response layout changed. Remaining maximum now returns as a string with a currency\nsymbol. Parser was casting to numeric and silently producing zero. Two days of verifications showed\n$0.00 remaining maximum on active plans before Danny flagged it in QA. Fixed, added a type guard,\nadded a test. Two days is too long and the reason it took two days is that nothing alerts on a\ndistribution shift in parsed values, only on parse failures.\n\n## 2026-07-08, Tue\n**Open Dental write-back incident, Lakeside Family Dental.**\nWrite-back created duplicate insurance plan records. 140 patient records affected. Cause: our\nwrite-back had no idempotency key, so a retried write after a timeout created a second plan row\nrather than updating the first. The retry path was added in June and never tested against a timeout.\n\n**Write-back is now disabled behind the `pms_writeback_enabled` feature flag, set to false for all\ncustomers, as of 2026-07-08.** Open Dental customers are receiving results via manual CSV export\nuntil this is fixed properly with an idempotency key and a reconciliation pass. Cleanup at Lakeside\ntook two days, mostly done by their office manager.\n\nRe-enabling is a Q3 roadmap item under PMS write-back reliability. No date yet. Nobody should be\ntelling customers or prospects that Open Dental write-back is automatic today, because it is not."
  },
  {
    "id": "eng-open-dental-runbook",
    "title": "Open Dental integration runbook",
    "department": "engineering",
    "source": "github",
    "owner": "Wes Okafor",
    "updated": "2026-05-22",
    "sensitivity": "internal",
    "body": "# Open Dental integration runbook\n\nOpen Dental is our most permissive integration and the one we recommend prospects be on. Direct API\naccess, no partner agreement, no middleware.\n\n## Setup\n\n1. Customer generates an API key in Open Dental under Setup > Advanced Setup > API. Needs the\n   Developer Key from us plus their own Customer Key.\n2. Confirm the version. We support 24.2 and above. Below that the appointment endpoint does not\n   return the insurance plan reference and the whole thing falls apart.\n3. Set the sync window. Default is 48 hours ahead, hourly.\n\n## Endpoints used\n\n- `GET /appointments` filtered by date range, for the schedule pull\n- `GET /patients/{id}` for demographics\n- `GET /insplans/{id}` and `GET /patplans` for the plan and subscriber relationship\n- `PUT /benefits` for write-back\n\n## Write-back\n\nVerification results are written back automatically once a verification completes. Benefit detail\nlands on the patient's insurance plan record as benefit rows, and the verification date is stamped\non the patplan record so the office can see freshness at a glance. No manual step, no export. This\nis the main reason Open Dental customers have the smoothest experience.\n\n## Common failure modes\n\n**Version drift.** Customer upgrades Open Dental, endpoint behaviour changes subtly. Check the\nversion on every failed sync before debugging anything else.\n\n**Duplicate patient records.** Practices create duplicates constantly. We match on patient ID, not\nname, so a duplicate means we verify one record and the front desk looks at the other. Nothing we\ncan fix from our side, flag it to the practice.\n\n**Local install, no static IP.** Some single-server installs sit behind a dynamic IP. Allowlisting\nbreaks weekly. Push them toward Open Dental's cloud hosting.\n\n**Replica lag.** Not applicable here, Open Dental API is against live. That is an Eaglesoft problem."
  },
  {
    "id": "eng-portal-change-detection",
    "title": "Portal change detection design notes",
    "department": "engineering",
    "source": "github",
    "owner": "Wes Okafor",
    "updated": "2026-04-30",
    "sensitivity": "internal",
    "body": "# Portal change detection\n\n## Why it exists\n\nPayer portals change without notice. When a layout changes, our parser either breaks loudly, which\nis fine, or silently extracts the wrong field, which is not. The Aetna currency string incident in\nJuly is the second category and cost us two days of bad maximums.\n\n## How it works today\n\nFor each payer we store a structural baseline of the eligibility response page: a normalised\nrepresentation of the DOM tree with text content stripped, element attributes reduced to tag,\nclass and position. Every poll cycle we render the page for a synthetic test member and diff the\nstructure against the baseline.\n\nDivergence above a threshold raises an alert to #eng-oncall and stamps the payer's\n`last_portal_change` field, which surfaces in the payer coverage summary.\n\n## Known problems\n\nThe threshold is a single number applied to the whole page. Payers put marketing content, session\nbanners and A/B tests on the same page as the benefit detail, so the detector cannot tell a layout\nchange that will break the parser from a promotional banner that will not. Current false positive\nrate is roughly 80%. See NT-318.\n\n## What it does not do\n\nIt does not detect policy changes. A payer can move a procedure from one benefit class to another\nwithout changing a single element of the page structure, and the detector will see nothing. The\nDelta Dental of California fluoride reclassification on 2026-06-01 was a policy change; the portal\nchange on 2026-06-02 was coincidental and separate.\n\nThis is the more important gap. Structural changes break the scraper and we find out in minutes.\nPolicy changes silently invalidate a playbook and we find out when QA catches misgraded\nverifications, or when a customer does.\n\n## Ideas not yet built\n\n- Golden-record checks: run a set of known members with known benefits and assert the extracted\n  values, rather than asserting the page structure. Catches both categories.\n- Distribution monitoring on parsed values. A sudden shift in the modal coinsurance for a payer is a\n  policy change signal.\n- Subscribe to payer provider bulletins. Unglamorous, probably the highest value item on this list."
  },
  {
    "id": "escalation-sop",
    "title": "Escalation SOP for verification exceptions",
    "department": "ops",
    "source": "notion",
    "owner": "Akhilesh T",
    "updated": "2026-07-30",
    "sensitivity": "phi-restricted",
    "body": "# Escalation SOP\n\nAn exception is any verification the agent could not complete with high confidence. This document is\nabout what a human does next. It is not about how the agent decides.\n\n## Tier 1, verifier resolves\nHandled in queue, target 15 minutes.\n- Portal returned a partial response, re-run\n- Member found under a different spelling or a dependent record\n- Group number missing from the PMS record, request from the practice\n- Benefit class needs a playbook lookup\n\n## Tier 2, team lead\nEscalate to Priya. Target 2 hours.\n- Portal says one thing and the playbook says another\n- Payer phone line gives an answer that contradicts the portal\n- Any verification where a call is required and the payer wait time exceeds 25 minutes\n- Same exception reason firing more than five times in a shift on one payer, which usually means a\n  portal change rather than five unrelated problems\n\n## Tier 3, RCM Lead\nEscalate to Akhilesh. Same day.\n- Any of the three critical misses in the QA rubric\n- A practice disputing a verification we issued\n- Suspected payer policy change affecting more than one group\n- Anything that will require a playbook edit\n\n## Tier 4, CTO\nEscalate to Nakul. Immediate.\n- Portal scraper failing across a whole payer\n- Any suspected exposure of patient data outside the platform\n- PMS write-back producing incorrect records at a customer site\n\n## Handling patient data during escalation\nNever paste member identifiers, dates of birth or subscriber IDs into Slack, including private\nchannels. Reference the verification ID only. The verification record already contains everything\nthe next person needs and is access controlled. This applies to screenshots as well, and screenshots\nare the most common way this rule gets broken.\n\n## After resolution\nEvery Tier 2 and above resolution requires the exception reason to be set on the verification record\nbefore closing. That field is what populates the coverage summary. A blank or \"other\" reason means\nthe resolution is invisible to everyone who was not in the room."
  },
  {
    "id": "ga-expense-policy",
    "title": "Expense policy",
    "department": "ga",
    "source": "drive",
    "owner": "Maya Iyer",
    "updated": "2026-05-09",
    "sensitivity": "internal",
    "body": "# Expense policy\n\nSmall company, few rules, one principle: spend it like it is yours and be able to explain it.\n\n## Approval thresholds\n\n| Amount | Approval |\n|---|---|\n| Under $200 | None, submit with receipt |\n| $200 to $1,000 | Your manager, before you spend |\n| $1,000 to $5,000 | Maya, before you spend |\n| Above $5,000 | Jofin, before you spend |\n\nRecurring software counts as annualised value, not monthly. A $90 per month tool is a $1,080\ndecision.\n\n## Travel\n\nBook economy on flights under six hours. Above six hours, premium economy is fine, business needs\nJofin. Book at least 14 days ahead where the trip is known, we are not paying walk-up fares because\nsomeone did not put it in the calendar.\n\nHotels: reasonable business standard. No per diem, submit actuals. Meals while travelling are\ncovered, alcohol is covered when it is a customer dinner and not otherwise.\n\nCustomer visits: always book refundable. Dental groups reschedule.\n\n## Home office\n\n$500 one-time on joining for desk setup, plus $50 per month toward internet for fully remote staff.\nMonitors and laptops are company assets, ordered by Maya, not expensed.\n\n## What needs no approval but does need a receipt\n\nCoffee with a candidate. Books. Conference tickets under $200. A domain name.\n\n## What is not covered\n\nPersonal phone bills, gym memberships, coworking day passes without prior approval, and anything\nwhere the receipt has been lost. If you lose a receipt, tell Maya before submitting rather than\nafter.\n\n## Submission\n\nMonthly, by the 5th, through the expense tool. Reimbursement lands with the following payroll run.\nAnything submitted after the 5th waits a month, which is not a punishment, it is just how the\npayroll cycle works."
  },
  {
    "id": "ga-pto-policy",
    "title": "PTO and leave policy",
    "department": "ga",
    "source": "drive",
    "owner": "Maya Iyer",
    "updated": "2026-01-15",
    "sensitivity": "public",
    "body": "# PTO and leave\n\n## Annual leave\n\n18 days per calendar year, plus public holidays in your location. Accrues monthly from your start\ndate. Pro-rated in your first year.\n\nCarry over up to 5 days into the following year. They expire at the end of March. We would rather\nyou took them.\n\n## Booking\n\nRequest in the HR system, tell your manager, and put it in the shared calendar. Two weeks notice for\nanything over three days, more for anything over a week. There is no approval theatre, but the\nverification queue does not pause, so the ops team coordinates cover between themselves before\nbooking. Priya keeps the shift roster.\n\n## Public holidays\n\nYou take the public holidays where you live. The US team takes US federal holidays. The India team\ntakes the standard list plus two floating days of their choosing.\n\n## Sick leave\n\nTake it. Tell your manager. There is no cap and there is no doctor's note requirement for anything\nunder five consecutive days. Do not work while sick, particularly on the verification queue, where\ntired mistakes become patient billing problems.\n\n## Parental leave\n\n16 weeks fully paid for the primary caregiver, 6 weeks fully paid for the secondary caregiver,\navailable from day one of employment. Phased return over four weeks at full pay if you want it.\n\n## Unpaid leave and sabbatical\n\nCase by case with Maya and Jofin. We have said yes to both so far.\n\n## The part that actually matters\n\nThe ops team runs a queue with an SLA and the temptation is to not take leave. Priya and Akhilesh\nare responsible for making sure that does not happen. If you are on the HITL team and you have taken\nfewer than 5 days by the end of June, that is a conversation, not an achievement."
  },
  {
    "id": "ga-vendor-list",
    "title": "Vendor and tooling list",
    "department": "ga",
    "source": "drive",
    "owner": "Maya Iyer",
    "updated": "2026-06-05",
    "sensitivity": "internal",
    "body": "# Vendors and tooling\n\nReviewed quarterly. Anything not on this list needs approval before purchase, per the expense policy.\n\n## Infrastructure and product\n\n| Vendor | Purpose | Owner | Renewal | Notes |\n|---|---|---|---|---|\n| AWS | Hosting, object store | Nakul | Monthly | BAA in place |\n| Neon | Postgres | Nakul | Annual, Nov | |\n| Anthropic | Model API | Nakul | Monthly | BAA in place |\n| Datadog | Monitoring | Wes | Annual, Feb | Most expensive line after AWS, review at renewal |\n| Sentry | Error tracking | Wes | Annual, Sep | |\n\n## Go to market\n\n| Vendor | Purpose | Owner | Renewal | Notes |\n|---|---|---|---|---|\n| HubSpot | CRM | Rhea | Annual, Mar | |\n| Apollo | Prospecting | Rhea | Annual, Jan | |\n| Gong | Call recording | Jofin | Annual, Aug | Renewal due, low usage, question it |\n\n## Internal\n\n| Vendor | Purpose | Owner | Renewal | Notes |\n|---|---|---|---|---|\n| Slack | Comms | Maya | Annual, Apr | |\n| Notion | Docs and wiki | Maya | Annual, Apr | |\n| Google Workspace | Email, Drive | Maya | Annual, Jul | |\n| Linear | Issue tracking | Nakul | Annual, May | Jira migration completed Feb 2026, historical tickets still referenced by NT- prefix |\n| Rippling | HR and payroll | Maya | Annual, Jan | Leave allowance reconfigured to 20 days March 2026, handbook not yet updated |\n\n## Compliance and legal\n\n| Vendor | Purpose | Owner | Renewal | Notes |\n|---|---|---|---|---|\n| Vanta | SOC 2 monitoring | Nakul | Annual, Oct | Type II audit window opens Nov |\n| Cooley | Legal counsel | Jofin | Retainer | |\n\n## Notes\n\nAnything touching patient data requires a signed BAA before first use, no exceptions, and Maya keeps\nthe countersigned copies. If you are evaluating a tool and it will see PHI, the BAA conversation\nhappens before the trial, not before the purchase."
  },
  {
    "id": "gtm-discovery-brightsmile",
    "title": "Discovery call notes, Bright Smile Dental Partners",
    "department": "gtm",
    "source": "crm",
    "owner": "Rhea Sharma",
    "updated": "2026-08-12",
    "sensitivity": "internal",
    "body": "# Bright Smile Dental Partners, discovery call\n\n**Date:** 2026-08-12\n**Attendees:** Marcus Deng (VP Revenue Cycle), Alicia Tran (Regional Ops Manager). Rhea, Tom.\n**Profile:** 34 locations across Texas, mostly DFW and Houston. Eaglesoft. Roughly 9,000\nverifications per month. Centralised RCM team of six in Plano.\n\n## Current state\n\nSix people, all in house, doing eligibility for 34 locations. Marcus says the team is \"permanently\ntwo days behind\" and that Monday and Tuesday are unrecoverable. They batch verifications for the\nfollowing week every Thursday and Friday, which means anything scheduled inside 48 hours goes\nunverified and the front desk quotes from the last known benefit.\n\nAsked about collections leakage from bad quotes. Alicia said they wrote off roughly $40k last year\nin patient balances they could not collect after quoting wrong, and that the real number is higher\nbecause a lot of it just becomes a discount at the desk.\n\n## The thing Marcus kept coming back to\n\nClaims status. He raised it three times unprompted. His team is checking eligibility in one system\nand claim status in another, and he wants both surfaced inside Eaglesoft where his people already\nlive. Direct quote from my notes: \"if I have to teach six people a third portal, I would rather keep\nthe backlog.\"\n\nThis is not our product today. I did not promise it. I said it was on the roadmap and that I would\nfind out where. Flagging for Jofin and Nakul, this is the second prospect this quarter to lead with\nclaims status rather than eligibility.\n\n## Technical\n\nEaglesoft, on-premise at each location with a central SQL replica in Plano. Tom flagged that our\nEaglesoft sync is read-heavy and that the nightly appointment pull can lag if their replica is\nbehind. Needs a follow up on their replication schedule.\n\n## Next steps\n\n- Tom to scope the Eaglesoft integration against their replica setup, by 2026-08-19\n- Rhea to send the pilot proposal, 30 day read-only\n- Marcus to get his COO on the second call\n- Open question: claims status timeline. Do not answer until Nakul confirms."
  },
  {
    "id": "gtm-discovery-cedarridge",
    "title": "Discovery call notes, Cedar Ridge Dental Group",
    "department": "gtm",
    "source": "crm",
    "owner": "Rhea Sharma",
    "updated": "2026-07-29",
    "sensitivity": "internal",
    "body": "# Cedar Ridge Dental Group, discovery call\n\n**Date:** 2026-07-29\n**Attendees:** Dr. Helen Vasquez (owner, clinical), Bryan Ochoa (Office Manager). Rhea.\n**Profile:** 9 locations, Oregon, Portland and Salem. Open Dental. Around 2,200 verifications per\nmonth. No dedicated RCM function.\n\n## Current state\n\nNo centralised team. Each office does its own verification, front desk staff between patients. Bryan\nestimates 40 to 60 minutes per day per location, which he described as \"the thing everyone does\nbadly because it is nobody's actual job\".\n\nThey are below our stated minimum volume. Flagging that for pricing.\n\n## What they care about\n\nDr. Vasquez is the decision maker and she is clinical, not operational. She does not care about\ncost per verification. She cares that patients get told the right number before treatment, because\nshe is the one who has the conversation when they get billed for something they thought was free.\nSell reliability, not efficiency.\n\n## What I told them about integration\n\nBryan asked directly whether results land back in Open Dental or whether his staff have to copy them\nacross. I said write-back to Open Dental is automatic, results appear on the patient's insurance\nplan record without anyone touching it. He said that was the difference between a yes and a no for\nhim.\n\nI should check that with Nakul before the follow up. I am going off the runbook.\n\n## Objections raised\n\n- Price. They are used to paying nothing because the labour is hidden in existing salaries. Bryan\n  did the maths out loud and got to a number that made him quiet. Expect a second round on this.\n- They have a Carestack migration \"maybe next year\". Did not sound funded.\n\n## Next steps\n\n- Rhea to check volume minimum with Jofin, they are at 2,200 against a 5,000 minimum\n- Confirm Open Dental write-back status with Nakul before the follow up call\n- Follow up scheduled 2026-08-14"
  },
  {
    "id": "gtm-discovery-northshore",
    "title": "Discovery call notes, Northshore Dental Alliance",
    "department": "gtm",
    "source": "crm",
    "owner": "Rhea Sharma",
    "updated": "2026-06-24",
    "sensitivity": "internal",
    "body": "# Northshore Dental Alliance, discovery call\n\n**Date:** 2026-06-24\n**Attendees:** Priyanka Rao (Director of RCM), Dev Chaudhry (Director of IT), Karen Whitfield (CFO,\njoined for the last 15 minutes). Rhea, Jofin.\n**Profile:** 112 locations, Illinois and Wisconsin. Dentrix Ascend. Roughly 31,000 verifications per\nmonth. Largest opportunity in the pipeline.\n\n## Current state\n\nHybrid. An offshore BPO in Manila handles the bulk, an in-house team of four in Milwaukee handles\nexceptions and anything requiring a phone call. Contract with the BPO renews in January, which is\nthe real deadline on this deal.\n\nPriyanka has the attempt to completion number and it is 1.6. She was the first prospect who has ever\nhad that number ready. She knows exactly what her effective cost per completed verification is and\nshe is not happy about it.\n\n## What matters to them\n\n1. Exception rate transparency. She wants to see, per payer, how often the automated pass fails and\n   why. Not a dashboard for its own sake, she wants to renegotiate her staffing model against it.\n2. Audit trail. Karen asked twice about how we evidence what was verified and when, in the event of\n   a payer audit or a patient dispute.\n3. Dentrix Ascend partner status. Dev asked whether we are a certified integration partner. We are\n   in process. Do not overstate this.\n\n## Risk\n\nDev is the blocker. He has been through two failed integrations and he opened by telling us so. He\nis not hostile, he is tired. He wants a named engineering contact and a rollback plan, not a sales\nprocess.\n\n## Next steps\n\n- Jofin to send exception rate data by payer, anonymised, as a proof point\n- Nakul to join call two as the named engineering contact for Dev\n- Confirm Dentrix Ascend partner agreement status before call two\n- Target: proposal by end of September, decision before the January BPO renewal"
  },
  {
    "id": "gtm-icp",
    "title": "Ideal customer profile",
    "department": "gtm",
    "source": "notion",
    "owner": "Jofin Joseph",
    "updated": "2026-05-16",
    "sensitivity": "internal",
    "body": "# ICP\n\n## Who we sell to\n\nMulti-location dental groups and DSOs, 8 to 150 locations, US only. Below 8 locations the pain is\nreal but the budget authority sits with an owner-dentist who is also chairside, and the sales cycle\nis long relative to the contract value. Above 150 the group usually has an offshore RCM team already\nand the conversation becomes a displacement fight rather than a greenfield one.\n\nSweet spot is 20 to 60 locations. Centralised RCM function, one or two people running eligibility\nfor the whole group, visible backlog, and enough volume that per-verification pricing produces a\nreal number without a procurement process.\n\n## Buyer\n\nPrimary: VP of Revenue Cycle, Director of RCM, or in smaller groups the Regional Operations Manager.\nThey own the backlog and feel it daily.\n\nEconomic buyer: COO or CFO. They care about cost per verification and about collections leakage from\nbad quotes, not about AI.\n\nBlocker: the IT or systems person who owns the PMS. If they have been burned by an integration\nbefore, they will slow everything down. Bring Tom in early rather than late.\n\n## Qualifying signals\n\n- Runs Open Dental, Dentrix Ascend, Carestack or Eaglesoft. Anything else is a custom build and we\n  should not be selling it yet.\n- Verification volume above 2,500 per month\n- Currently doing eligibility in house or with an offshore BPO\n- Has had a collections problem traced back to a bad quote in the last year. This is the single best\n  signal. Ask about it directly.\n\n## Disqualifying signals\n\n- Single location or fully owner-operated\n- Wants us to do full claims submission today. We do eligibility. Say so.\n- Wants a per-seat licence rather than per-verification. The model does not work and the\n  conversation is a distraction.\n\n## Why they buy\n\nNot cost. Every group we have won has bought because their existing process is unreliable in a way\nthat shows up at the front desk. Cost is how they justify it internally. Reliability is why they\ncall."
  },
  {
    "id": "gtm-lost-deal-valleyoak",
    "title": "Lost deal post-mortem, Valley Oak Dental Group",
    "department": "gtm",
    "source": "crm",
    "owner": "Jofin Joseph",
    "updated": "2026-07-18",
    "sensitivity": "internal",
    "body": "# Lost deal post-mortem: Valley Oak Dental Group\n\n**Profile:** 22 locations, Arizona. Carestack. Around 6,400 verifications per month.\n**Cycle:** First call 2026-04-02, lost 2026-07-16 to an offshore BPO incumbent extending scope.\n**Owner:** Rhea, with Jofin on calls two and four.\n\n## What happened\n\nWe were the preferred option through call three. Their Director of RCM, Nadia Halabi, told us\ndirectly that our exception handling was the only version of this she had seen that she believed.\nWe lost on price, and specifically on how we presented price.\n\n## Root cause\n\nRhea quoted flat $1.75 per verification with a 5,000 per month minimum, from the pricing sheet, on\n2026-04-08. Our tiered pricing went live on 2026-04-15, one week later. At 6,400 verifications per\nmonth Valley Oak sits inside the first band so the headline rate would have been the same, but the\ntiered structure was the thing that would have won the argument, because Nadia's board question was\n\"what happens to this number when we acquire and go to 25,000 a month\".\n\nUnder the flat sheet the answer was \"it goes up linearly\". Under the tiered model the answer is\n\"your unit cost drops to $1.40\". We gave the first answer. The incumbent gave a volume commitment\ndiscount and won the room.\n\nNobody had told Rhea the pricing changed. The sheet in Drive still said flat.\n\n## Contributing factors\n\n- Three week gap between call three and the proposal, over which the incumbent got a second meeting\n- We never got to their CFO. Nadia carried our case internally and lost it without us in the room\n- Carestack integration scoping took eleven days and we did not communicate during it\n\n## Actions\n\n1. Pricing sheet in Drive is stale. It still says flat $1.75 with a 5,000 minimum. Current model\n   since 2026-04-15 is tiered: $1.75 up to 20k per month, $1.40 for 20k to 75k, $1.15 above 75k,\n   minimum 2,500 per month. Objection handling doc quotes the old number too. Both need updating.\n   **Owner: Jofin. Still open as of this writing.**\n2. Any deal above 15 locations gets a CFO on the call before proposal. Non-negotiable.\n3. Integration scoping gets a status note to the prospect every third day even when there is nothing\n   to report.\n\n## The uncomfortable version\n\nWe lost a deal because a document was three months out of date and the person using it had no way to\nknow. That is not a sales problem."
  },
  {
    "id": "gtm-objection-handling",
    "title": "Objection handling",
    "department": "gtm",
    "source": "notion",
    "owner": "Rhea Sharma",
    "updated": "2026-02-27",
    "sensitivity": "internal",
    "body": "# Objection handling\n\n## \"We already have an offshore team doing this\"\n\nDo not attack the team. Ask two questions: what percentage of verifications come back needing\nre-work, and how long the queue is on a Monday morning. Most groups do not know the first number and\nwince at the second. The pitch is not \"replace your team\", it is \"your team stops doing the 70% that\nis mechanical and starts doing the 30% that needs a phone call\".\n\n## \"How is this different from the AI tools we keep getting pitched?\"\n\nEvery one of those returns a payer response and calls it done. We put a human on every exception\nbefore it reaches your front desk. Ask them what happens today when the portal returns something\nambiguous. That is the whole difference and it is worth a full minute.\n\n## \"$1.75 is more than we pay now\"\n\nYou pay per attempt, we charge per completed verification. Ask for their attempt to completion\nratio. If they run 1.4 attempts per completed verification at $1.30, they are at $1.82 and they have\na queue.\n\n## \"We had a bad integration experience\"\n\nAlmost always Dentrix or a custom middleware project. Acknowledge it, do not argue. Offer a\nread-only pilot: we pull the schedule, we return verifications, nothing writes back to their system\nuntil they have seen 30 days of output they trust. Bring Tom Beckett to the second call.\n\n## \"Can you do claims too?\"\n\nNot today. Say that clearly. Then ask what happens when a claim comes back denied and whether they\ncan trace it to the eligibility check. Nobody can. That is the roadmap conversation and it is a\nbetter one than pretending we do claims.\n\n## \"We need to talk to our PMS vendor first\"\n\nFine, but find out whether that is a real dependency or a delay tactic. Open Dental and Carestack\nare permissive. Eaglesoft is slower. Dentrix Ascend needs a partner agreement that takes weeks, so\nif they are on Dentrix Ascend, start that paperwork on the first call."
  },
  {
    "id": "gtm-pricing-notes",
    "title": "Pricing notes and discount guidance",
    "department": "gtm",
    "source": "drive",
    "owner": "Jofin Joseph",
    "updated": "2026-01-20",
    "sensitivity": "internal",
    "body": "# Pricing\n\n## Model\n\nPer completed verification. We do not charge for failed or duplicate verifications, and this matters\nin the pitch because the incumbent BPOs charge per attempt.\n\n**Rate: $1.75 per verification.**\n**Minimum: 5,000 verifications per month, billed monthly in arrears.**\n\nA 30 location group running roughly 250 verifications per location per month lands around 7,500 per\nmonth, so the minimum is rarely the binding constraint for a group in our ICP band.\n\n## What is included\n\n- Eligibility and benefit verification across all supported payers\n- Human QA on every exception\n- PMS integration and write-back where supported\n- Standard SLA: 95% of verifications returned within 4 business hours, 99% within 24\n\n## Discount guidance\n\nUp to 10% off list without approval, for annual prepay only. Above 10% needs Jofin. Do not discount\nthe minimum, discount the rate, the minimum is what makes the unit economics work at the small end.\n\nNever discount below $1.40. Below that the human QA layer stops paying for itself at current\nexception rates.\n\n## Competitive context\n\nThe offshore BPOs come in between $1.10 and $1.60 per attempt, which usually works out higher per\ncompleted verification once you account for their re-work rate. Get the prospect to tell you their\ncompletion rate. Most have never measured it.\n\nThe software-only tools price per location per month, typically $150 to $400. That looks cheaper to\na CFO on a spreadsheet. The counter is that they return a raw payer response and someone at the\ngroup still has to read it, so the group is paying for software and still paying for labour.\n\n## Payment terms\n\nNet 30. Annual prepay gets the discount. No multi-year without Jofin, we are changing the product\ntoo fast to lock a rate for three years."
  },
  {
    "id": "hitl-verifier-onboarding",
    "title": "New verifier onboarding, first two weeks",
    "department": "ops",
    "source": "notion",
    "owner": "Priya Menon",
    "updated": "2026-08-04",
    "sensitivity": "phi-restricted",
    "body": "# New verifier onboarding\n\nWritten for people joining the human-in-the-loop team with dental front office or RCM experience but\nno Needletail experience. Two weeks to independent queue work.\n\n## Week 1\n\n**Days 1 to 2.** HIPAA training and platform access. You will not touch a live verification until\ntraining is signed off. Read the escalation SOP and the QA rubric before anything else. Understand\nthat everything you see in the queue is patient data and the rules about where it can go are not\nnegotiable.\n\n**Days 3 to 5.** Shadow queue. You work verifications alongside a reviewer who checks every one\nbefore it goes out. You will be slow. Everyone is slow. Speed comes from knowing which payer does\nwhat, and that takes about three weeks, not three days.\n\nStart with Delta Dental of California and Cigna. They are the highest volume and the most\npredictable. Do not start on Aetna or Guardian.\n\n## Week 2\n\nLive queue at 100% QA sampling. You own the verification, a QA analyst scores all of it. Target is\n95 on the rubric, not speed. Turnaround is 5% of your score for a reason.\n\n## What the agent has already done before you see it\n\nBy the time a verification reaches your queue, the agent has attempted the portal, parsed the\nresponse and assigned a confidence. You are seeing it because the confidence was low or a rule fired.\nYour job is not to redo the work, it is to resolve the specific thing the agent could not.\n\nRead the exception reason first. It tells you what to look at.\n\n## The thing new verifiers get wrong most often\n\nTrusting the playbook over the portal, or the portal over the playbook, without noticing they\ndisagree. When they disagree, that is the finding. Escalate it rather than picking one. A\ndisagreement between the playbook and the portal usually means the payer changed something and\nnobody has updated us yet, and you are the first person to see it.\n\nAsk in #verification-help. Nobody has ever been in trouble here for asking about a frequency rule.\nPeople have been in trouble for guessing one."
  },
  {
    "id": "payer-aetna",
    "title": "Aetna Dental verification playbook",
    "department": "ops",
    "source": "notion",
    "owner": "Akhilesh T",
    "updated": "2026-07-14",
    "sensitivity": "internal",
    "body": "# Aetna Dental\n\nFourth by volume, highest exception rate of the big five at 4.2%. Almost all of that is the\nalternate benefit provision on posterior composites.\n\n## The downgrade problem\nAetna applies an alternate benefit provision: a composite filling on a posterior tooth (D2391,\nD2392, D2393, D2394) is paid at the amalgam rate (D2140 through D2161). The patient owes the\ndifference. The portal does not flag this on the eligibility response. It is buried in the plan\nbooklet.\n\nThis matters because a practice quoting from our verification will under-quote the patient by\nroughly $80 to $140 per surface, and that becomes a collections problem for them and a trust\nproblem for us. Always add the downgrade note when the treatment plan includes a posterior\ncomposite code. NT-312 is the ticket to detect this automatically.\n\n## Access\nAetna provider portal via Availity. Availity session and Aetna session expire independently, which\nis why you sometimes get logged into Availity but see an Aetna authentication error. Log out of both\nand back in rather than refreshing.\n\n## Frequency rules\n- D1110 prophy: 2 per calendar year on most groups, 2 per 12 rolling months on DMO\n- D0274 bitewings: 1 per calendar year\n- D0210 FMX: 1 per 36 months\n- D4910 perio maintenance: 4 per calendar year but shares a counter with D1110 on many groups, so\n  4 total cleanings of any type, not 4 plus 2\n\n## Portal change, July 2026\nThe eligibility response layout changed on 2026-07-09. The remaining maximum field is now returned\nas a string with a currency symbol rather than a number, which broke downstream parsing for two\ndays. Fixed, but if you see a maximum of $0.00 on an otherwise active plan, re-run before trusting.\n\n## Trust the portal or call\nTrust for eligibility and maximum. Call for the alternate benefit provision detail on any group you\nhave not seen before, and for orthodontic benefits on DMO plans."
  },
  {
    "id": "payer-cigna",
    "title": "Cigna Dental verification playbook",
    "department": "ops",
    "source": "notion",
    "owner": "Priya Menon",
    "updated": "2026-05-02",
    "sensitivity": "internal",
    "body": "# Cigna Dental\n\nThird by volume. The cleanest portal of the big five for routine preventive work, and the most\npainful for anything restorative because of waiting periods and the missing tooth clause.\n\n## Access\nCigna for Health Care Professionals portal. Single sign on per TIN. Sessions are stable, no tab\nlimit issues.\n\n## The missing tooth clause\nThis is our top exception reason for Cigna and it is worth understanding rather than escalating\nblind. If a tooth was extracted before the member's effective date, the plan will not pay for the\nprosthetic that replaces it, even years later. The portal does not tell you when a tooth was\nextracted. It only tells you the clause applies to the group.\n\nPractical rule: if the clause applies and the treatment plan includes D6010, D6240, D6750 or any\npartial or full denture code, mark the verification as conditional and note \"missing tooth clause\napplies, prior extraction date required from patient records\". Do not guess.\n\n## Waiting periods\nBasic 3 months, Major 6 months, Ortho 12 months on standard groups. New hire groups often waive\nBasic. The portal shows the waiting period at plan level but not the member's original effective\ndate if they changed groups within the same employer, which is why we occasionally have to call.\n\n## Frequency rules\n- D1110 prophy: 2 per calendar year\n- D0150 comprehensive exam: 1 per 36 months per provider\n- D0274 bitewings: 1 per calendar year\n- D4910 perio maintenance: 2 per calendar year, does not share a counter with prophy on most groups\n\n## Trust the portal or call\nTrust for eligibility, deductible, maximum, waiting period status. Call for missing tooth clause\ndetail and for any DHMO plan, since Cigna's DHMO benefit tables are not exposed to the portal at all."
  },
  {
    "id": "payer-coverage-summary",
    "title": "Payer coverage summary, top 10 by volume",
    "department": "ops",
    "source": "verification-db",
    "owner": "Nakul R",
    "updated": "2026-08-25",
    "sensitivity": "internal",
    "body": "# Payer coverage summary\n\nGenerated nightly from the verification database. Lifetime figures since platform launch. Exception\nrate is the share of verifications that could not be completed without human intervention.\n\nTotal verifications: 240,400. Blended exception rate: 3.4%.\n\n| Payer | Verifications | Exception rate | Top exception reason | Last portal change |\n|---|---|---|---|---|\n| Delta Dental of California | 52,400 | 2.4% | Fluoride benefit class ambiguity (D1206) | 2026-06-02 |\n| MetLife | 41,200 | 3.1% | Perio maintenance frequency (D4910) | 2026-05-18 |\n| Cigna Dental | 33,700 | 2.9% | Missing tooth clause, prior extraction date unknown | 2026-04-27 |\n| Aetna Dental | 28,900 | 4.2% | Posterior composite downgrade (D2392) | 2026-07-09 |\n| Guardian | 22,150 | 3.6% | Ortho lifetime maximum not exposed in portal | 2026-03-11 |\n| UnitedHealthcare Dental | 17,400 | 5.1% | Portal timeout, no real-time response | 2026-07-22 |\n| Humana Dental | 14,800 | 3.3% | Plan type mismatch, PPO vs DHMO | 2026-02-19 |\n| Ameritas | 11,600 | 2.7% | Frequency counted on service year not calendar year | 2026-05-05 |\n| Principal | 9,300 | 3.8% | Coordination of benefits, secondary payer | 2026-06-30 |\n| BCBS regional plans | 8,950 | 6.4% | Regional plan routing ambiguity | 2026-07-15 |\n\n## Reading this table\n\nException rate is the cost driver. Every point of exception rate is roughly 2,400 additional human\ntouches across the book at current volume. UnitedHealthcare and BCBS are the two payers where the\nexception rate is driven by portal reliability rather than benefit complexity, which means they are\nfixable with engineering rather than with better playbooks.\n\nThe \"last portal change\" column is populated by the portal change detector (see NT-318). A change\ndate within the last 30 days on a payer with a rising exception rate is the signal that a playbook\nhas gone stale. Delta Dental of California changed on 2026-06-02 and its top exception reason has\nbeen fluoride benefit class ever since.\n\n## Known gaps in this data\n- Exception reason is assigned by the QA analyst at resolution time and is free text mapped to a\n  fixed list. Roughly 6% of exceptions are tagged \"other\" and are not represented above.\n- We do not currently join eligibility outcome to claim outcome. We know when a verification was\n  hard, we do not know when it was wrong."
  },
  {
    "id": "payer-delta-ca",
    "title": "Delta Dental of California verification playbook",
    "department": "ops",
    "source": "notion",
    "owner": "Akhilesh T",
    "updated": "2026-02-11",
    "sensitivity": "internal",
    "body": "# Delta Dental of California\n\nHighest volume payer on the platform. Generally well behaved. Real-time eligibility returns in under\n40 seconds on the provider portal for most PPO groups.\n\n## Access\nProvider Tools portal, shared service account. Session times out after 20 minutes idle. Do not open\nmore than three tabs against one session, the portal starts returning blank benefit panels rather\nthan an error.\n\n## Benefit classes\n\n| Class | Typical coinsurance | Notes |\n|---|---|---|\n| Diagnostic and Preventive | 100%, deductible waived | D0120, D0150, D1110, D1120 |\n| Basic | 80% after deductible | D2140-D2394 restorative, D1206 adult fluoride, D7140 simple ext |\n| Major | 50% after deductible, 12 month wait on some groups | D2740, D2750, D6010 |\n\nAdult fluoride varnish D1206 sits under Basic and takes the 80% coinsurance with deductible applied.\nVerifiers get this wrong regularly because most other payers treat it as preventive. Flag it in the\nnotes field so the practice does not quote the patient zero out of pocket.\n\n## Frequency rules\n- D1110 adult prophy: 2 per calendar year, portal counter is reliable\n- D0274 bitewings: 1 per calendar year\n- D0210 full mouth series: 1 per 36 months, portal shows last service date\n- D1206 fluoride: 1 per calendar year, age 19 and over only on groups with the adult rider\n\n## Trust the portal or call\nTrust the portal for eligibility status, plan maximum, deductible remaining and prophy history.\nCall for: orthodontic lifetime maximum where the member has prior ortho history, coordination of\nbenefits when a secondary payer is listed, and any group number beginning 77xxx (these are\nself-funded ASO groups and the portal shows the administrator's default schedule, not the group's).\n\n## Common exceptions\nBenefit class ambiguity on fluoride is our top exception reason for this payer. Second most common\nis a missing group number on the patient record in the PMS, which is a practice-side data problem,\nnot a payer problem. Route those back to the office rather than escalating."
  },
  {
    "id": "payer-guardian",
    "title": "Guardian verification playbook",
    "department": "ops",
    "source": "notion",
    "owner": "Priya Menon",
    "updated": "2026-04-08",
    "sensitivity": "internal",
    "body": "# Guardian\n\nFifth by volume. Straightforward for general dentistry, consistently difficult for orthodontics.\n\n## Access\nGuardian Anytime provider portal. Requires provider NPI. The portal is single threaded per account,\na second concurrent session silently invalidates the first, so verifiers must not share the account\nduring the same shift block. Check the shift roster before logging in.\n\n## The orthodontic problem\nGuardian's orthodontic lifetime maximum is not exposed on the eligibility response. This is our top\nexception reason for this payer. The portal shows whether ortho is covered and at what coinsurance,\nbut not how much of the lifetime maximum the member has already consumed. For a member who had\ntreatment under a previous employer's Guardian plan, the remaining maximum can be zero while the\nportal shows the benefit as active.\n\nRule: any treatment plan containing D8080, D8090 or D8670 on a Guardian member gets a phone\nverification. No exceptions, no matter what the portal says. A wrong ortho quote is a five figure\nmistake for the practice.\n\n## Frequency rules\n- D1110 prophy: 2 per calendar year\n- D1206 fluoride: through age 18 on standard groups, adult rider available\n- D0274 bitewings: 1 per calendar year\n- D2740 crown: 1 per tooth per 60 months, portal shows prior crown history reliably\n\n## Waiting periods\nBasic none, Major 6 months, Ortho 12 months. Guardian is one of the few payers that reliably shows\nthe member's original effective date, so waiting period calculation is usually safe from the portal.\n\n## Portal change, March 2026\nProvider search moved from NPI-first to TIN-first on 2026-03-11. Old bookmarked deep links return a\n404. Use the portal home page and navigate, do not bookmark."
  },
  {
    "id": "payer-metlife",
    "title": "MetLife verification playbook",
    "department": "ops",
    "source": "notion",
    "owner": "Akhilesh T",
    "updated": "2026-03-04",
    "sensitivity": "internal",
    "body": "# MetLife\n\nSecond highest volume payer. The portal is fast but shallow. Most of our exceptions here come from\nthe portal answering a question it does not actually have the data to answer.\n\n## Access\nMetDental provider portal. Requires TIN plus provider last name. The account locks after five failed\nattempts and takes a business day to unlock, so do not retry a failing login more than twice.\n\n## Benefit classes\n- Preventive: 100%, deductible waived, D0120 D0150 D1110 D1206\n- Basic: 80% after deductible, includes D4341 and D4342 scaling and root planing\n- Major: 50%, 6 month waiting period on most groups, 12 on new hires\n\n## Frequency rules\n- D1110 prophy: 2 per calendar year\n- D4910 perio maintenance: 4 per calendar year, the portal frequency counter shows remaining and\n  can be trusted\n- D0274 bitewings: 2 per calendar year, unusually generous, confirm before quoting\n- D2740 crown: 1 per tooth per 60 months\n\n## Trust the portal or call\nTrust for eligibility, plan max, deductible. Call for anything involving a history of periodontal\ntreatment, and for any member whose plan name contains \"Preferred Dentist Program Plus\" since those\ngroups carry riders the portal does not surface.\n\n## Portal quirk, May 2026\nThe benefit detail panel moved from a right hand column to a collapsible accordion below the member\nsummary on 2026-05-18. Our scraper broke for about six hours. If you see a verification come through\nwith plan maximum populated but every frequency field empty, that is the accordion not being\nexpanded, re-run it rather than calling.\n\n## Common denial codes seen downstream\n- 271: frequency limitation exceeded, almost always D4910 or D1110\n- 149: procedure not covered under the member's plan\n- W7: missing tooth clause applies"
  },
  {
    "id": "product-feedback-digest",
    "title": "Customer feedback digest, July 2026",
    "department": "product",
    "source": "drive",
    "owner": "Jofin Joseph",
    "updated": "2026-08-03",
    "sensitivity": "internal",
    "body": "# Customer feedback digest, July 2026\n\nCompiled from support tickets, QBR notes and two customer calls. Six live customers.\n\n## Recurring themes\n\n**1. \"Where did this answer come from?\" (4 of 6 customers)**\nThe single most common request. Practices want to see which payer response and which rule produced\na verification result, especially when they disagree with it. Summit Dental Collective's RCM lead\ndescribed the current output as \"an answer with no working out\". This is a trust problem, not a\nfeature gap, and it gets worse as we automate more.\n\n**2. Claim status (3 of 6 customers, plus 2 open prospects)**\nSame request from every direction. Covered in PRD-014.\n\n**3. Turnaround variance, not average (2 of 6)**\nOur SLA is 95% within 4 business hours. Customers do not experience the 95%, they experience the\n5%. Lakeside asked for a per-verification ETA rather than a blanket SLA, because their front desk\ncannot plan around an average.\n\n## Specific incidents\n\n**Lakeside Family Dental, 2026-07-08.** Duplicate insurance plan records created in Open Dental by\nour write-back. 140 patient records affected, cleaned up manually over two days by their office\nmanager and Wes. Write-back disabled behind a flag the same day. Lakeside were reasonable about it,\nwhich we should not mistake for it being fine.\n\n**Summit Dental Collective, 2026-07-22.** Batch of 60 Aetna verifications went out without the\nposterior composite downgrade note during a week when the notes rule was mis-scoped. Caught by their\nown front desk, not by us. Rubric now treats this as a critical miss.\n\n## What nobody asked for\n\nNo customer has asked for a dashboard, a mobile app, or AI-generated summaries of their verification\nvolume. Two have asked for a CSV export they can put in their own BI tool. Worth remembering before\nwe build reporting.\n\n## Quote worth keeping\n\nSummit's RCM lead, on why they signed: \"I do not need it to be right every time. I need to know\nwhich ones it was not sure about.\" That is the product."
  },
  {
    "id": "product-prd-claims-status",
    "title": "PRD-014 Claims status v1",
    "department": "product",
    "source": "notion",
    "owner": "Nakul R",
    "updated": "2026-08-06",
    "sensitivity": "internal",
    "body": "# PRD-014: Claims status v1\n\n**Status:** Approved, not started. Target: end Q3 2026.\n**Owner:** Nakul R.\n\n## Problem\n\nA practice verifies eligibility with us, treats the patient, submits a claim, and the claim comes\nback denied. Today there is no link between those two events. The practice cannot tell whether the\ndenial was caused by a bad verification, a coding error, or a payer decision that no verification\nwould have caught. Neither can we.\n\nTwo commercial consequences. First, prospects keep asking for claim status in the same breath as\neligibility, most recently Bright Smile Dental Partners on 2026-08-12. Second, and more important\ninternally, we have no accuracy measure. Our exception rate tells us which verifications were hard.\nIt tells us nothing about which ones were wrong.\n\n## Scope, v1\n\n**In:**\n- Read-only claim status pulled from payer portals for claims linked to a verification we issued\n- Status surfaced on the verification record: submitted, in process, paid, denied, with denial code\n- Denial code mapped to our exception reason taxonomy where a mapping exists\n- Backfill of the last 90 days where the payer portal exposes history\n\n**Out:**\n- Claim submission\n- Appeals or resubmission workflow\n- Any write-back of claim status into the PMS\n- Payers outside the top 5 by volume for v1\n\n## Success criteria\n\n1. For at least 60% of denied claims linked to one of our verifications, we can say whether the\n   denial was foreseeable from the eligibility response.\n2. Verification-to-denial rate available per payer, per benefit class, in the coverage summary.\n3. Bright Smile pilot can see claim status next to eligibility without leaving their workflow.\n\n## The metric we actually want\n\nForeseeable denial rate: the share of denials that a correct verification would have predicted.\nThat number, per payer, is the first honest accuracy measure we will have. It is also the number\nthat turns the verification corpus into training signal rather than a log.\n\n## Open questions\n\n- Do we need a BAA amendment for claim-level data? Legal to confirm.\n- Eaglesoft has no claim status API. Screen scrape or defer Eaglesoft to v2?"
  },
  {
    "id": "product-roadmap-q3",
    "title": "Product roadmap Q3 2026",
    "department": "product",
    "source": "notion",
    "owner": "Jofin Joseph",
    "updated": "2026-07-05",
    "sensitivity": "internal",
    "body": "# Roadmap, Q3 2026\n\nThree themes. Everything else is explicitly not happening this quarter.\n\n## Theme 1: reduce exception rate on the two worst payers\n\nUnitedHealthcare at 5.1% and BCBS regional at 6.4% are both reliability problems, not benefit\ncomplexity problems. UHC times out, BCBS routes to the wrong regional plan. Neither needs a better\nplaybook, both need engineering.\n\nTarget: UHC below 3.5%, BCBS below 4.5% by end of quarter.\n\n- Retry and backoff strategy for UHC portal timeouts\n- Regional plan routing table for BCBS, built from the last 12 months of resolved exceptions\n- NT-318 portal change detector false positive cleanup, so the signal is trustworthy\n\n## Theme 2: claims status v1 (PRD-014)\n\nSecond quarter running that prospects have led with claims status rather than eligibility. Bright\nSmile raised it three times unprompted on discovery. Northshore's CFO asked about audit trail, which\nis adjacent.\n\nScope for v1 is read-only status surfaced next to the eligibility record. Not submission, not\nappeals, not denial management. Nakul owns. See PRD-014.\n\nThe strategic reason this matters more than it looks: joining eligibility to claim outcome is what\nlets us know when a verification was wrong, not just when it was hard. Today we measure difficulty.\nWe do not measure accuracy.\n\n## Theme 3: PMS write-back reliability\n\nOpen Dental write-back is currently disabled behind a flag after the Lakeside duplicate plan record\nincident. Getting it back on with proper idempotency is the priority. Eaglesoft sync lag at Bright\nSmile scale is the second.\n\n## Explicitly not this quarter\n\n- Claims submission\n- Dentrix Ascend certified partner integration, paperwork is in flight but the build is Q4\n- Any new payer beyond the current top 10\n- Self-serve onboarding"
  },
  {
    "id": "product-ticket-nt312",
    "title": "NT-312 Detect Aetna posterior composite downgrade automatically",
    "department": "product",
    "source": "jira",
    "owner": "Nakul R",
    "updated": "2026-08-18",
    "sensitivity": "internal",
    "body": "# NT-312: Detect Aetna posterior composite downgrade automatically\n\n**Type:** Story\n**Priority:** High\n**Status:** In progress\n**Assignee:** Wes Okafor\n**Reporter:** Akhilesh T\n**Sprint:** 2026-08-17\n\n## Description\n\nAetna applies an alternate benefit provision on posterior composite restorations. D2391, D2392,\nD2393 and D2394 are paid at the corresponding amalgam rate (D2140 to D2161) and the patient owes the\ndifference. The eligibility response does not flag this. It is in the plan booklet only.\n\nVerifiers are expected to add a downgrade note manually when the treatment plan includes one of\nthese codes. This is one of three critical misses in the QA rubric and it is the most frequently\nmissed of the three. The Summit Dental Collective incident on 2026-07-22 was 60 verifications going\nout without the note.\n\nAetna is our highest exception rate payer in the top five at 4.2% and this is the top exception\nreason.\n\n## Acceptance criteria\n\n- [ ] When a treatment plan on an Aetna member contains D2391-D2394, the verification record carries\n      a `downgrade_applies` flag\n- [ ] The flag renders as a required note on the verifier's screen and cannot be dismissed without a\n      reason\n- [ ] Estimated patient responsibility difference is calculated from the group's amalgam allowable\n      where we have it, and left blank rather than guessed where we do not\n- [ ] Flag appears in the customer-facing verification output\n- [ ] Backfill not required\n\n## Notes\n\nAkhilesh: do not extend this to other payers without checking. Several payers have an alternate\nbenefit provision and the code sets are not identical. Getting this wrong on Cigna would be worse\nthan not having it.\n\nWes: group allowable amounts are only available for about 60% of Aetna groups. Handling the other\n40% as blank rather than estimating, per acceptance criteria."
  },
  {
    "id": "product-ticket-nt318",
    "title": "NT-318 Portal change detector false positives",
    "department": "product",
    "source": "jira",
    "owner": "Nakul R",
    "updated": "2026-08-21",
    "sensitivity": "internal",
    "body": "# NT-318: Portal change detector producing false positives\n\n**Type:** Bug\n**Priority:** Medium\n**Status:** Open\n**Assignee:** Unassigned\n**Reporter:** Priya Menon\n**Sprint:** Unscheduled\n\n## Description\n\nThe portal change detector compares the DOM structure of each payer portal's eligibility response\npage against a stored baseline and raises an alert when it diverges. The alert populates the \"last\nportal change\" field in the payer coverage summary and pages the on-call engineer.\n\nIt is firing roughly four times a week and approximately one in five of those is a real change. The\nrest are A/B tests, promotional banners, session-specific content and in one case a payer's holiday\nmessage. On-call has started ignoring the alert, which defeats the purpose.\n\n## Why this matters more than a medium priority bug usually does\n\nThe last-portal-change date is the signal ops uses to decide whether a playbook has gone stale. The\nDelta Dental of California fluoride reclassification on 2026-06-01 was accompanied by a real portal\nchange on 2026-06-02, and that alert was in the same noise as everything else. Nobody acted on it\nuntil Danny caught the misgraded verifications in QA nine days later.\n\nA change detector that nobody trusts is worse than no change detector, because it creates the\nimpression that stale playbooks would have been caught.\n\n## Suggested approach\n\n- Diff only the benefit detail region, not the whole page\n- Require the divergence to persist across three consecutive polls before alerting\n- Suppress alerts where the diff is text-only within a known static region\n- Separate \"structure changed, scraper may break\" from \"content changed, playbook may be stale\".\n  These are different alerts for different people.\n\n## Notes\n\nPriya: the second alert type is the one ops needs and it does not exist today. The engineering alert\nexists and is noisy. The ops alert does not exist at all."
  },
  {
    "id": "qa-rubric",
    "title": "Verification QA rubric v3",
    "department": "ops",
    "source": "notion",
    "owner": "Danny Alvarez",
    "updated": "2026-06-20",
    "sensitivity": "internal",
    "body": "# Verification QA rubric v3\n\nEvery verifier has 10% of their completed verifications sampled and scored. New verifiers are\nsampled at 100% for their first two weeks, then 25% until they clear two consecutive weeks above 95.\n\n## Scoring\n\nEach sampled verification is scored out of 100 across five dimensions.\n\n| Dimension | Weight | What a miss looks like |\n|---|---|---|\n| Eligibility accuracy | 30 | Active/inactive wrong, wrong effective date, wrong plan |\n| Benefit detail accuracy | 30 | Wrong coinsurance, wrong benefit class, wrong deductible |\n| Frequency accuracy | 20 | Frequency limit wrong or history misread |\n| Notes and flags | 15 | Missing downgrade note, missing conditional flag, missing COB flag |\n| Turnaround | 5 | Outside the SLA band for the queue |\n\n## Thresholds\n- 95 and above: pass\n- 90 to 94: pass with coaching note\n- Below 90: fail, verification is re-worked and the verifier gets a review session\n- Any eligibility accuracy miss is an automatic fail regardless of total score\n\n## Critical misses\nThree categories are treated as critical and are escalated to the RCM Lead the same day, regardless\nof the overall score:\n1. Quoting a patient zero out of pocket on a procedure that is not actually covered at 100%\n2. Missing an orthodontic lifetime maximum check on Guardian\n3. Missing a posterior composite downgrade note on Aetna\n\nThese three account for the large majority of practice-reported errors. They are also the three\ncases where the portal actively misleads you, which is why they are rubric-level rather than\ncoaching-level.\n\n## Calibration\nDanny and Priya independently score the same 20 verifications every second Friday and compare. If\ninter-rater agreement drops below 90% the rubric wording gets revised rather than the scores. v3\nwas written after the May calibration showed disagreement on what counted as a notes miss."
  },
  {
    "id": "slack-fluoride-delta-june",
    "title": "Slack thread, Delta Dental CA moved adult fluoride to preventive",
    "department": "ops",
    "source": "slack",
    "owner": "Priya Menon",
    "updated": "2026-06-11",
    "sensitivity": "internal",
    "body": "# #verification-help, 2026-06-11\n\n**Danny Alvarez** (11:03)\nSomething changed on Delta CA. I have scored four verifications this morning where the verifier put\nadult fluoride D1206 under Basic at 80% per the playbook, and the portal is showing it at 100% no\ndeductible. That is not a one-off, it is every group I have looked at.\n\n**Priya Menon** (11:19)\nI saw the same thing on Friday and assumed it was a rendering issue after the layout change. Let me\ncall.\n\n**Priya Menon** (12:40)\nConfirmed with Delta. Adult fluoride varnish D1206 moved from Basic to Diagnostic and Preventive\neffective 2026-06-01. 100% coinsurance, deductible waived, same as a prophy. The annual frequency is\nunchanged, still 1 per calendar year for members 19 and over on groups carrying the adult rider.\n\nThe rep said it went out in a provider bulletin in April. We did not see it.\n\n**Priya Menon** (12:44)\nAlso relevant: the portal layout changed on 2026-06-02, the day after the policy change. The benefit\nclass now renders in the collapsible panel under the member summary rather than in the class table\non the right. So even people who were looking in the right place were looking in the wrong place.\n\n**Sam Ortiz** (12:58)\nSo for anything from June onwards, fluoride is preventive at 100%?\n\n**Priya Menon** (13:01)\nFor Delta Dental of California, yes. Effective 2026-06-01. Do not generalise it to other Delta\nmember companies, I have not checked those, and definitely do not generalise it to other payers.\n\n**Danny Alvarez** (13:07)\nRe-working the four I scored. Also this is going to be our top exception reason for Delta CA for a\nwhile until the playbook catches up, because the agent is answering off the playbook and the QA pass\nis catching it after the fact.\n\n**Priya Menon** (13:15)\nThe playbook says Basic. Someone needs to edit the playbook. @Akhilesh T\n\n**Akhilesh T** (16:22)\nAck. Adding to the list."
  },
  {
    "id": "slack-metlife-perio-edge",
    "title": "Slack thread, MetLife perio maintenance frequency edge case",
    "department": "ops",
    "source": "slack",
    "owner": "Priya Menon",
    "updated": "2026-07-02",
    "sensitivity": "internal",
    "body": "# #verification-help, 2026-07-02\n\n**Sam Ortiz** (09:14)\nQuestion on a MetLife one. Member has had D4910 three times this year already, portal frequency\ncounter says 1 remaining out of 4. Treatment plan has another perio maintenance in September. The\nplaybook says 4 per calendar year and trust the counter. Do I just mark it covered?\n\n**Priya Menon** (09:22)\nHold on that one. What is the group name?\n\n**Sam Ortiz** (09:24)\nPlan name is \"Preferred Dentist Program\", group 4417xx. Not the Plus version.\n\n**Priya Menon** (09:31)\nThen no, do not mark it covered off the counter. Tagging @Akhilesh T because this comes up\nconstantly and the playbook is out of date on it.\n\n**Akhilesh T** (09:47)\nRight, so this is the single most expensive mistake we make on MetLife. The playbook says 4 per\ncalendar year. That is only true for groups carrying the enhanced perio rider. On a standard group\nit is 2 per calendar year. The portal counter shows 4 for everyone because it is rendering the\nplan's maximum possible frequency, not the group's actual one.\n\nSo the counter saying \"1 remaining\" on a standard group means the member is already two over. If we\nquote that as covered the practice bills it, MetLife denies with a 271, and the patient gets a\nsurprise bill for a cleaning they were told was free.\n\n**Akhilesh T** (09:49)\nRule going forward: any D4910 on MetLife where the member already has two or more this calendar\nyear, call. Do not trust the counter. If the plan name ends in \"Plus\" you can trust 4.\n\n**Sam Ortiz** (09:52)\nGot it. Calling. Should the playbook get updated?\n\n**Akhilesh T** (09:55)\nYes. It is on my list. It has been on my list since about March, which tells you something about\nhow well the list works.\n\n**Danny Alvarez** (10:12)\nAdding this to the coaching notes. This is behind a decent chunk of our MetLife exception volume."
  }
];

const BY_ID = new Map(CORPUS.map((d) => [d.id, d]));

export function getDoc(id: string): Doc | undefined {
  return BY_ID.get(id);
}

export function docExists(id: string): boolean {
  return BY_ID.has(id);
}

/** Metadata only. This is what goes into the doc-selection prompt. */
export const CORPUS_INDEX: DocMeta[] = CORPUS.map(({ body, ...meta }) => meta);

export function docMeta(id: string): DocMeta | undefined {
  const d = BY_ID.get(id);
  if (!d) return undefined;
  const { body, ...meta } = d;
  return meta;
}
